
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class BioadataSiswaTugas extends javax.swing.JFrame {
    
    private final DefaultTableModel tabelModel;
    String nama;
    String kelas;
    String ttl;
    String rombel;
    String jk;
    String hobi;
    String cita;
    String alamat;
    String noHp;

    /**
     * Creates new form BioadataSiswaTugas
     */
    public BioadataSiswaTugas() {
        initComponents();
        setLocationRelativeTo(null);
        tabelModel = (DefaultTableModel) tabeldata.getModel();
        hobi = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbKelas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtttl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rblaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtcita = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hobi_game = new javax.swing.JCheckBox();
        hobi_baca = new javax.swing.JCheckBox();
        hobi_belanja = new javax.swing.JCheckBox();
        hobi_olahraga = new javax.swing.JCheckBox();
        hobi_travel = new javax.swing.JCheckBox();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        btnReset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtnohp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtrombel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("NAMA LENGKAP");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("BIODATA SISWA");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("KELAS");

        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "XI", "XII" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("TTL");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setText("JENIS KELAMIN");

        rblaki.setText("LAKI-LAKI");
        rblaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblakiActionPerformed(evt);
            }
        });

        rbperempuan.setText("PEREMPUAN");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setText("CITA-CITA");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setText("HOBI");

        hobi_game.setText("BERMAIN GAME");
        hobi_game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hobi_gameActionPerformed(evt);
            }
        });

        hobi_baca.setText("MEMBACA");
        hobi_baca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hobi_bacaActionPerformed(evt);
            }
        });

        hobi_belanja.setText("BELANJA");
        hobi_belanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hobi_belanjaActionPerformed(evt);
            }
        });

        hobi_olahraga.setText("OLAHRAGA");
        hobi_olahraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hobi_olahragaActionPerformed(evt);
            }
        });

        hobi_travel.setText("TRAVELING");
        hobi_travel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hobi_travelActionPerformed(evt);
            }
        });

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAMA", "KELAS", "TITL", "ROMBEL", "JENIS KELAMIN", "CITA-CITA", "HOBI", "ALAMAT", "NO HP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabeldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldata);

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setText("ALAMAT");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel9.setText("NO HP");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel10.setText("ROMBEL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNama)
                                .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtttl)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rblaki)
                                    .addGap(43, 43, 43)
                                    .addComponent(rbperempuan))
                                .addComponent(txtcita, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                                .addComponent(txtrombel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hobi_game)
                                    .addComponent(hobi_olahraga))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hobi_travel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(hobi_baca)
                                        .addGap(18, 18, 18)
                                        .addComponent(hobi_belanja))))
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(51, 51, 51)
                                .addComponent(btnReset))
                            .addComponent(txtnohp, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtttl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtrombel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(rblaki)
                    .addComponent(rbperempuan))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtcita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hobi_game)
                        .addComponent(hobi_baca)
                        .addComponent(hobi_belanja)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hobi_travel)
                    .addComponent(hobi_olahraga))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtnohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnSimpan))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rblakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rblakiActionPerformed

    private void hobi_gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hobi_gameActionPerformed
        // TODO add your handling code here:
        if(hobi_game.isSelected()) {
            hobi = hobi + "" + hobi_game.getText() + ",";
        } else {
            hobi = "";
        }
    }//GEN-LAST:event_hobi_gameActionPerformed

    private void hobi_bacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hobi_bacaActionPerformed
        // TODO add your handling code here:
        if(hobi_baca.isSelected()) {
            hobi = hobi + "" + hobi_baca.getText() + ",";
        } else {
            hobi = "";
        }
    }//GEN-LAST:event_hobi_bacaActionPerformed

    private void hobi_belanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hobi_belanjaActionPerformed
        // TODO add your handling code here:
        if(hobi_belanja.isSelected()) {
            hobi = hobi + "" + hobi_belanja.getText() + ",";
        } else {
            hobi = "";
        }
    }//GEN-LAST:event_hobi_belanjaActionPerformed

    private void hobi_olahragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hobi_olahragaActionPerformed
        // TODO add your handling code here:
        if(hobi_olahraga.isSelected()) {
            hobi = hobi + "" + hobi_olahraga.getText() + ",";
        } else {
            hobi = "";
        }
    }//GEN-LAST:event_hobi_olahragaActionPerformed

    private void hobi_travelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hobi_travelActionPerformed
        // TODO add your handling code here:
        if(hobi_travel.isSelected()) {
            hobi = hobi + "" + hobi_travel.getText() + ",";
        } else {
            hobi = "";
        }
    }//GEN-LAST:event_hobi_travelActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        nama = txtNama.getText();
        kelas = cbKelas.getSelectedItem().toString();
        ttl = txtttl.getText();
        if(rblaki.isSelected()) {
            jk = rblaki.getText();
        } else if(rbperempuan.isSelected()) {
            jk = rbperempuan.getText();
        }
        cita = txtcita.getText();
        rombel = txtrombel.getText();
        alamat = txtalamat.getText();
        noHp = txtnohp.getText();

        Object[]data = new Object[9];
        data[0] = nama;
        data[1] = kelas;
        data[2] = ttl;
        data[3] = rombel;
        data[4] = jk;
        data[5] = cita;
        data[6] = hobi;
        data[7] = alamat;
        data[8] = noHp;
        tabelModel.addRow(data);
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tabeldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldataMouseClicked
        // TODO add your handling code here:
        int baris = tabeldata.rowAtPoint(evt.getPoint());
        String nama = tabeldata.getValueAt(baris, 0).toString();
        txtNama.setText(nama);
        String kelas = tabeldata.getValueAt(baris, 1).toString();
        cbKelas.setSelectedItem(kelas);
        String ttl = tabeldata.getValueAt(baris, 2).toString();
        txtttl.setText(ttl);
        String rombel = tabeldata.getValueAt(baris, 3).toString();
        txtrombel.setText(rombel);
        String jk = tabeldata.getValueAt(baris, 4).toString();
        if(jk == "LAKI-LAKI") {
            rblaki.setSelected(true);
            rbperempuan.setSelected(false);
        } else {
            rbperempuan.setSelected(true);
            rblaki.setSelected(false);
        }
        String[] hobiArray = hobi.split(",\\s*");
        System.out.println(hobiArray);
        String[] hasilArray = new String[hobiArray.length];
        for (int i = 0; i < hobiArray.length; i++) {
            String aktivitas = hobiArray[i];
            hasilArray[i] = aktivitas;
        }
        
        System.out.println("Hasil array:");
        for (String aktivitas : hasilArray) {
            System.out.println(aktivitas);
        }

        String cita = tabeldata.getValueAt(baris, 5).toString();
        txtcita.setText(cita);
        String alamat = tabeldata.getValueAt(baris, 7).toString();
        txtalamat.setText(alamat);
        String nohp = tabeldata.getValueAt(baris, 8).toString();
        txtnohp.setText(nohp);
    }//GEN-LAST:event_tabeldataMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtNama.setText("");
        txtttl.setText("");
        txtcita.setText("");
        txtrombel.setText("");
        txtalamat.setText("");
        txtnohp.setText("");
        rblaki.setSelected(false);
        rbperempuan.setSelected(false);
        cbKelas.setSelectedItem("X");
        hobi_game.setSelected(false);
        hobi_olahraga.setSelected(false);
        hobi_baca.setSelected(false);
        hobi_travel.setSelected(false);
        hobi_belanja.setSelected(false);
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BioadataSiswaTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BioadataSiswaTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BioadataSiswaTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BioadataSiswaTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BioadataSiswaTugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JCheckBox hobi_baca;
    private javax.swing.JCheckBox hobi_belanja;
    private javax.swing.JCheckBox hobi_game;
    private javax.swing.JCheckBox hobi_olahraga;
    private javax.swing.JCheckBox hobi_travel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JTable tabeldata;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtcita;
    private javax.swing.JTextField txtnohp;
    private javax.swing.JTextField txtrombel;
    private javax.swing.JTextField txtttl;
    // End of variables declaration//GEN-END:variables
}
